# Site settings
title: Jakob Endler - Data Engineer
email: jakob@endler.tech
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Jakob, a passionate Data Engineer based in Bonn.
  This is my digital homebase :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://endler.tech" # the base hostname & protocol for your site
instagram_username: jakob_endler
github_username:  JEndler

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings

# Posts settings
permalink: pretty
future: true

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Navigation
nav:
  - label: Projects
    url: /projects/
  - label: About
    url: /about/
